// <auto-generated />
using System;
using LogicaAccesoDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicaAccesoDatos.Migrations
{
    [DbContext(typeof(PlataformaContext))]
    [Migration("20230920032551_PrimerMig")]
    partial class PrimerMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogicaNegocio.Dominio.Amenaza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EcosistemaId")
                        .HasColumnType("int");

                    b.Property<int?>("EspecieMarinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EcosistemaId");

                    b.HasIndex("EspecieMarinaId");

                    b.ToTable("Amenazas");
                });

            modelBuilder.Entity("LogicaNegocio.Ecosistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Ecosistemas");
                });

            modelBuilder.Entity("LogicaNegocio.EspecieMarina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EcosistemaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EcosistemaId");

                    b.ToTable("EspecieMarinas");
                });

            modelBuilder.Entity("LogicaNegocio.EstadoConservacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("EstadoConservacions");
                });

            modelBuilder.Entity("LogicaNegocio.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EcosistemaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EcosistemaId");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("LogicaNegocio.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("UsuarioAutorizado");
                });

            modelBuilder.Entity("LogicaNegocio.Dominio.Amenaza", b =>
                {
                    b.HasOne("LogicaNegocio.Ecosistema", null)
                        .WithMany("Amenazas")
                        .HasForeignKey("EcosistemaId");

                    b.HasOne("LogicaNegocio.EspecieMarina", null)
                        .WithMany("amenazas")
                        .HasForeignKey("EspecieMarinaId");
                });

            modelBuilder.Entity("LogicaNegocio.EspecieMarina", b =>
                {
                    b.HasOne("LogicaNegocio.Ecosistema", null)
                        .WithMany("EspecieMarinas")
                        .HasForeignKey("EcosistemaId");
                });

            modelBuilder.Entity("LogicaNegocio.Pais", b =>
                {
                    b.HasOne("LogicaNegocio.Ecosistema", null)
                        .WithMany("Pais")
                        .HasForeignKey("EcosistemaId");
                });

            modelBuilder.Entity("LogicaNegocio.Ecosistema", b =>
                {
                    b.Navigation("Amenazas");

                    b.Navigation("EspecieMarinas");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("LogicaNegocio.EspecieMarina", b =>
                {
                    b.Navigation("amenazas");
                });
#pragma warning restore 612, 618
        }
    }
}
